### ISSUE TITLE
Github document output format

### ISSUE THREAD

**Issue by ellen-ying** [knickodem/kfa#10]
The tables in the report don't seem to render well when the output format is markdown document. They don't show in the output at all.

**Comment by knickodem** [comment]
This requires some adjustment to how the flextables are rendered, which should be possible. To ensure the changes suit your needs, can you give me a little more information on how you will use the subsequent markdown file?

**Comment by ellen-ying** [comment]
I would like to post it on my github repo so that the team can preview the doc more conveniently. 

Thank you very much!

**Comment by knickodem** [comment]
Currently, the tables are formatted in the report with [flextable which does not support rendering to a .md file](https://davidgohel.github.io/flextable/reference/knit_print.flextable.html). When `report.format = "md_document"`, the flextables, as well as the plots from semPlot, are output to a separate folder as .png files. Consequently, producing the tables in a .md file will require creating a separate reporting workflow.
