### ISSUE TITLE
kfa_report error message

### ISSUE THREAD

**Issue by carly-n-hobbes** [knickodem/kfa#12]
Hi Kyle! Hope all is well. Using kfa on some data analysis, and I encountered the following error message when trying to run the report:

```
processing file: kfa-report.Rmd
  |.......................................................                                       |  59% [details]           
Quitting from lines 87-162 [details] (kfa-report.Rmd)
Error in `data.frame()`:
! arguments imply differing number of rows: 124, 1, 141
Backtrace:
  1. base::suppressWarnings(...)
  4. semPlot (local) `<fn>`(...)
  6. semPlot (local) `<fn>`(`<lavaan>`, mplusStd = "std")
  8. semPlot::semPlotModel_S4(object)
  9. semPlot (local) .local(object, ...)
 10. base::data.frame(...)
```
Not sure if this is something on my end or your end ...? The models themselves run fine, as do the aggregated loading tables, models, etc - happy to share my data and syntax as is useful.

**Comment by brianmsm** [comment]
This seems to be related to a change in the internal way of storing lavaan information that changed from version 0.6-14, and that semPlot is not handling it well:

https://github.com/knickodem/kfa/issues/11#issuecomment-1439013532
